### PR TITLE
add packages for 4.08.0+beta2

### PR DESCRIPTION
**Pull request by damiendoligez**

### CODE REVIEW

**Comment by damiendoligez** [comment]
@avsm could you review and merge? When that's done I can announce beta2 to the world.

**Comment by gasche** [comment]
I hadn't realized that this was not opam-repository anymore, so the mergers pool is much smaller, and also I hadn't realized that I had merge rights. This is now merged.

**Comment by damiendoligez** [comment]
Thanks.

**Comment by avsm** [comment]
Thanks! I was teaching all day yesterday -- you should have merge rights as well @damiendoligez ... checking now!

**Comment by avsm** [comment]
opam-dev, caml-devel, and opam-repository members all have merge access here...

**Pull request merged**
